### ISSUE TITLE
Run and crash

### ISSUE THREAD

**Issue by JamesAX** [jhuckaby/Cronicle#145]
## Steps to reproduce the problem

create a http task and run

### Node.js version?

10.15.0

## Log Excerpts

![image](https://user-images.githubusercontent.com/5799935/51241336-8bb3bd00-19b8-11e9-92b6-2928c278ffad.png)

**Comment by jhuckaby** [comment]
Please see [Issue #133](https://github.com/jhuckaby/Cronicle/issues/133) -- this may have a solution for you, if you are using the Shell Plugin, and you have a "hardened" server which doesn't allow executables from the temp directory.

**Comment by fl4p** [comment]
I have similar issue:
```
[Error][error][job][Failed to exec ps: Error: spawn /bin/sh EAGAIN][]
[Error][error][job][Failed to exec ps: Error: spawn /bin/sh EAGAIN][]
[Error][error][crash][Emergency Shutdown: TypeError: Cannot read property 'setEncoding' of undefined][]
```

```
tail crash.log 
TypeError: Cannot read property 'setEncoding' of undefined
    at __construct.init (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:40:17)
    at new __construct (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:31:8)
    at constructor.launchLocalJob (/opt/cronicle/lib/job.js:602:17)
    at constructor.monitorInternalQueue (/opt/cronicle/lib/queue.js:51:18)
    at __construct.emit (events.js:202:15)
    at __construct.tick (/opt/cronicle/node_modules/pixl-server/server.js:349:8)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
```

I have cronicle running for a year without this error. I guess I'm hitting systems memory limit now.
Would be cool if Cronicle didn't crash on job start failure

**Comment by jhuckaby** [comment]
The `EAGAIN` error means you're hitting the per-user process limit on the server, `ulimit -u`.  Meaning, you are trying to spawn too many simultaneous processes at once.

This is a very rare error so I didn't plan for it.  However, I will look into the crash, so it doesn't affect the Cronicle daemon.
