### ISSUE TITLE
Setup an API Key through config.json

### ISSUE THREAD

**Issue by fabiopedrosa** [jhuckaby/Cronicle#205]
I'd like to make our automation a bit better by having the ability to start cronicle with a pre-defined API key, so we can avoid creating one manually. Is that something easy to add?

**Comment by jhuckaby** [comment]
Sure, you can do this now.  It isn't officially documented, but here is how:

When you first install Cronicle, you generally run the following command once, which initializes storage (this is [documented here](https://github.com/jhuckaby/Cronicle#setup)):

```
/opt/cronicle/bin/control.sh setup
```

This command actually follows a set of actions defined in the [setup.json](https://github.com/jhuckaby/Cronicle/blob/master/sample_conf/setup.json) file, which is shipped with Cronicle and installed here on your server: `/opt/cronicle/conf/setup.json`.  You can actually edit this file *before you run the above command*, and add any additional storage records you want to create, including API keys.

Here is how that is done.  First, open the file and locate this item:

```json
[ "listCreate", "global/api_keys", {} ]
```

This creates the empty list for API keys.  Just after this, you can add a special `listPush` command to push items onto the `global/api_keys` list, which is where API keys are stored.  So for example, consider this:

```json
[ "listCreate", "global/api_keys", {} ],
[ "listPush", "global/api_keys", {
	"privileges": {
		"admin": 0,
		"create_events": 1,
		"edit_events": 1,
		"delete_events": 1,
		"run_events": 1,
		"abort_events": 0,
		"state_update": 0
	},
	"active": "1",
	"title": "Fabio's Test App",
	"description": "It does things.",
	"id": "93fe0f04",
	"key": "0095f5b664b93304d5f8b1a61df605fb",
	"username": "admin",
	"modified": 1454300467,
	"created": 1441659908
} ],
```

Then save and close the file.  Then, when you run the `setup` command to initialize storage, this would actually push an API Key onto the list as part of the bootstrapping process.  In this case my example key has the following properties:

| Property | Value | Description |
|-|-|-|
| `privileges` | (Object) |  |
| `active` | `1` | This identifies the key as "active" in the system.  Inactive keys cannot be used. |
| `title` | `"Fabio's Test App"` | Enter the API Key title here, for display purposes. |
| `description` | `"It does things"` | Optionally provide a description here, but if you choose to omit, make sure you still include the `description` key set to an empty string (""). |
| `id` | `"93fe0f04"` | This is an internal ID for the API Key.  Set this to any random alphanumeric string. |
| `key` | `"0095f5b664b93304d5f8b1a61df605fb"` | This is the actual API Key itself, used for API calls.  This should also be alphanumeric. |
| `username` | `"admin"` | The user who created the key.  I recommend always setting this to `admin` because this will be the only user at the time of setup. |
| `modified` | `1454300467` | The last modification date of the key, expressed in Epoch seconds. |
| `created` | `1441659908` | The initial creation date of the key, expressed in Epoch seconds. |

Remember, the JSON syntax has to be **EXACT** for this to work.  One single typo and the whole thing will crash and burn.  I highly recommend you use a JSON validation app to make sure the JSON file is well-formed.  Also, **all** the properties above are required.

Hope this helps.  Good luck!

**Comment by fabiopedrosa** [comment]
@jhuckaby This worked perfectly. Thank you!

**Comment by fabiopedrosa** [comment]
@jhuckaby Might have spoken too soon. Cronicle is shutting down when I then do a request to the API to get the schedule:


```
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    | [1563304462.981][2019-07-16 19:14:22][pf-us1-smdev2][7][API][debug][9][Activating namespaced API handler: app/api_get_schedule for URI: /api/app/get_schedule][]
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    | [1563304462.984][2019-07-16 19:14:22][pf-us1-smdev2][7][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'session_id' of null][TypeError: Cannot read property 'session_id' of null     at constructor.loadSession (/opt/cronicle/lib/api.js:388:102)     at constructor.api_get_schedule (/opt/cronicle/lib/api/event.js:24:8)     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:86:21)     at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:835:12)     at constructor.filterHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:712:44)     at IncomingMessage.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:696:11)     at IncomingMessage.emit (events.js:182:13)     at endReadableNT (_stream_readable.js:1092:12)     at process._tickCallback (internal/process/next_tick.js:63:19)]
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    | [1563304462.984][2019-07-16 19:14:22][pf-us1-smdev2][7][Error][error][crash][Emergency Shutdown: TypeError: Cannot read property 'session_id' of null][]
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    | [1563304462.985][2019-07-16 19:14:22][pf-us1-smdev2][7][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read property 'session_id' of null][]
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    | TypeError: Cannot read property 'session_id' of null
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at constructor.loadSession (/opt/cronicle/lib/api.js:388:102)
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at constructor.api_get_schedule (/opt/cronicle/lib/api/event.js:24:8)
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:86:21)
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:835:12)
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at constructor.filterHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:712:44)
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at IncomingMessage.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:696:11)
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at IncomingMessage.emit (events.js:182:13)
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at endReadableNT (_stream_readable.js:1092:12)
cronicle.1.1la3q5ci56nw@pf-us1-smdev2    |     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by jhuckaby** [comment]
That is a very bizarre crash, and doesn't seem to have anything to do with our manual API key creation.  How are you making the API request to get the schedule?  Can I see the request code?  It's crashing at a very unexpected and obscure bit of code.

**Comment by fabiopedrosa** [comment]
@jhuckaby Sorry, it was actually a silly mistake on my end. Was performing a PUT instead of a GET there. It's working as it should now.

One last question, would it be easy for you to add an ENV var to set the pid_file PATH? I'm using cronicle using docker, and most of the time the container gets killed without cleaning the pid file, which makes follow up runs fail. The thing is, I need to mount the logs folder but wish the pid_file stayed inside the docker container.

**Comment by jhuckaby** [comment]
Actually, you found a real bug.  Even though you sent in a PUT, it should **not** be able to crash the entire server.  That's totally something I need to fix, and I will.  Thanks!

I will try to make the PID file configurable by ENV var, but I have to be really careful here because the master control shell script ([control.sh](https://github.com/jhuckaby/Cronicle/blob/master/bin/control.sh)) is expecting it to live in the `logs/` directory.  So I have to change that shell script to honor the ENV var, if it exists.  There may be a few other places it is used as well.  This may take a while, but I'll get to it as soon as I can.

Thanks again!

**Comment by VincentSurelle** [comment]
I also have the same behaviour when making a request on this path :

```
11/03/2020 09:18:30[1583914710.852][2020-03-11 08:18:30][7eb6d33f3e54][29][WebServer][debug][8][New incoming HTTP connection: c12][{"ip":"::ffff:xxx.xxx.xxx.xxx","num_conns":3}]
11/03/2020 09:18:30[1583914710.854][2020-03-11 08:18:30][7eb6d33f3e54][29][WebServer][debug][8][New HTTP request: GET /api/app/get_schedule/v1?limit=10000 (xxx.xxx.xxx.xxx)][{"socket":"c12","version":"1.1"}]
11/03/2020 09:18:30[1583914710.854][2020-03-11 08:18:30][7eb6d33f3e54][29][WebServer][debug][9][Incoming HTTP Headers:][{"host":"yyy.yyy.yyy.yyy:3012","user-agent":"GuzzleHttp/6.3.3 curl/7.54.1 PHP/7.1.8","accept":"application/json","content-type":"application/json","x-api-key":"xxxxxxxxxxxxxxxx","content-length":"4"}]
11/03/2020 09:18:30[1583914710.855][2020-03-11 08:18:30][7eb6d33f3e54][29][WebServer][debug][6][Invoking handler for request: GET /api/app/get_schedule/v1: API][]
11/03/2020 09:18:30[1583914710.856][2020-03-11 08:18:30][7eb6d33f3e54][29][API][debug][6][Handling API request: GET /api/app/get_schedule/v1?limit=10000][]
11/03/2020 09:18:30[1583914710.856][2020-03-11 08:18:30][7eb6d33f3e54][29][API][debug][9][API Params][]
11/03/2020 09:18:30[1583914710.857][2020-03-11 08:18:30][7eb6d33f3e54][29][API][debug][9][Activating namespaced API handler: app/api_get_schedule for URI: /api/app/get_schedule/v1][]
11/03/2020 09:18:30[1583914710.859][2020-03-11 08:18:30][7eb6d33f3e54][29][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'session_id' of null][TypeError: Cannot read property 'session_id' of null     at constructor.loadSession (/opt/cronicle/lib/api.js:388:102)     at constructor.api_get_schedule (/opt/cronicle/lib/api/event.js:24:8)     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:86:21)     at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:925:12)     at constructor.filterHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:795:44)     at IncomingMessage.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:779:11)     at IncomingMessage.emit (events.js:323:22)     at endReadableNT (_stream_readable.js:1204:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21)]
11/03/2020 09:18:30[1583914710.859][2020-03-11 08:18:30][7eb6d33f3e54][29][Error][error][crash][Emergency Shutdown: TypeError: Cannot read property 'session_id' of null][]
11/03/2020 09:18:30[1583914710.86][2020-03-11 08:18:30][7eb6d33f3e54][29][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read property 'session_id' of null][]
11/03/2020 09:18:30TypeError: Cannot read property 'session_id' of null
11/03/2020 09:18:30    at constructor.loadSession (/opt/cronicle/lib/api.js:388:102)
11/03/2020 09:18:30    at constructor.api_get_schedule (/opt/cronicle/lib/api/event.js:24:8)
11/03/2020 09:18:30    at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:86:21)
11/03/2020 09:18:30    at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:925:12)
11/03/2020 09:18:30    at constructor.filterHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:795:44)
11/03/2020 09:18:30    at IncomingMessage.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:779:11)
11/03/2020 09:18:30    at IncomingMessage.emit (events.js:323:22)
11/03/2020 09:18:30    at endReadableNT (_stream_readable.js:1204:12)
11/03/2020 09:18:30    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I can't really understand why a GET request can crash the entire server :/

Running the latest version of Cronicle on Node latest LTS

**Comment by VincentSurelle** [comment]
Actually it seem that `args.params` is undefined or null causing the error.

A quick'n'dirty fix is to add :

```javascript
if (!args.params) {
    args.params = {}
}
```

before line 388 of `lib/api.js` : https://github.com/jhuckaby/Cronicle/blob/8c563e2dff8f4206c2e9342b482381f0e1ec50b0/lib/api.js#L388

**Comment by jhuckaby** [comment]
Okay, I will add crash protection for this, but I have to say, you are sending in a **very** strange, bizarre HTTP request.  You are supposedly sending in an HTTP GET, but those should never have any body (content) except the URL and headers.  But yours has this:

```
"content-type":"application/json",
"content-length":"4"
```

An HTTP GET should never have a `Content-Type` header, and certainly not a `Content-Length`.  This has confused the request parser, because these are supposed to be for HTTP POST only.

So I will try to fix this and add protection so it doesn't crash, but something is very wrong with your request.  Probably the PHP libcurl stuff you are using.

Thanks for catching this.

**Comment by jhuckaby** [comment]
Fixed in [v0.8.45](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.45).  Looks like you were sending in these 4 bytes as the POST content body: `true`.  This exact 4-byte sequence gets passed the JSON parser, as it is technically a valid JSON document, but deep inner code is expecting an object, not a boolean.
