### ISSUE TITLE
Set encoding Error

### ISSUE THREAD

**Issue by ray-matos-mpf** [jhuckaby/Cronicle#220]
```
[1568820340.254][2019-09-18 15:25:40][instadrone.io][897][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'setEncoding' of undefined][TypeError: Cannot read property 'setEncoding' of undefined     at __construct.init (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:40:17)     at new __construct (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:31:8)     at constructor.launchLocalJob (/opt/cronicle/lib/job.js:602:17)     at /opt/cronicle/lib/job.js:245:11     at /opt/cronicle/node_modules/async/dist/async.js:3874:9     at /opt/cronicle/node_modules/async/dist/async.js:473:16     at replenish (/opt/cronicle/node_modules/async/dist/async.js:993:25)     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)     at /opt/cronicle/node_modules/async/dist/async.js:958:16     at /opt/cronicle/node_modules/async/dist/async.js:3871:13]
```

Version 0.8.31

**Comment by jhuckaby** [comment]
Very strange.  I have never seen this particular crash before.  May I ask what operating system and OS version you are on?

If the spawned child has no STDIN / STDOUT streams, then something truly horrible happened.  Is it possible that your server was completely out of memory when it tried to start the job?
