### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by sekys** [jhuckaby/Cronicle#223]
## Summary
Hello, 

today we had problem - Cronicle crashed after we tried several times bad password.

Thank you guys for great system

## Steps to reproduce the problem
Try several times bad password

### Operating system and version?
Amazon linux 2

### Node.js version?
v10.14.2

### Cronicle software version?
Version 0.8.31

### Are you using a multi-server setup, or just a single server?
1 master 4 slaves
Problem is at master server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
filesystem 

### Can you reproduce the crash consistently?
yes

## Log Excerpts
`[1570448330.098][2019-10-07 11:38:50][master.xxx.com][21990][Cronicle][debug][5][New socket.io client connected: FD9szj6Bb8fzNPDjAAAA (IP: ::ffff:127.0.0.1)][]
[1570448330.357][2019-10-07 11:38:50][master.xxx.com][21990][Cronicle][debug][1][Uncaught Exception: AssertionError [ERR_ASSERTION]: Wrong number of arguments to doError][AssertionError [ERR_ASSERTION]: Wrong number of arguments to doError     at constructor.doError (/opt/cronicle/node_modules/pixl-server-user/user.js:1305:3)     at /opt/cronicle/node_modules/pixl-server-user/user.js:308:17     at /opt/cronicle/node_modules/pixl-server-user/user.js:1281:5     at /opt/cronicle/node_modules/pixl-server-storage/storage.js:359:4     at /opt/cronicle/node_modules/pixl-server-storage/engines/Filesystem.js:422:4     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)]
[1570448330.357][2019-10-07 11:38:50][master.xxx.com][21990][Cronicle][debug][1][Emergency Shutdown: AssertionError [ERR_ASSERTION]: Wrong number of arguments to doError][]
`

We have to reset password and then restart server.

**Comment by jhuckaby** [comment]
Thanks, this was fixed in an external library: https://github.com/jhuckaby/pixl-server-user/pull/2

I just tagged a new release of that, so the next time you install or upgrade Cronicle, it'll grab the latest version of pixl-server-user which fixes this bug.

To force the fix to go in right away, you can:

```
cd /opt/cronicle
bin/control.sh stop
npm install
bin/control.sh start
```

Thanks!
