### ISSUE TITLE
Possible crash when choosing certain server selection algorithms

### ISSUE THREAD

**Issue by jhuckaby** [jhuckaby/Cronicle#23]
I received the following bug report via e-mail:

```
We are using it from quite a couple of months but we ended up in a crash recently when we tried to create a new server group and tried running the job on that group as a target.

Can you please help us in this regard, we are also trying to look into this. Find below the logs

Stack trace (in crash.log):
Tue Apr 11 2017 12:30:00 GMT+0000 (UTC)
TypeError: Cannot read property 'hostname' of null
    at constructor.chooseServer (/home/deployer/cronicle/Cronicle-0.6.11/lib/job.js:338:45)
    at /home/deployer/cronicle/Cronicle-0.6.11/lib/job.js:118:25
    at /home/deployer/cronicle/Cronicle-0.6.11/node_modules/async/lib/async.js:726:13
    at /home/deployer/cronicle/Cronicle-0.6.11/node_modules/async/lib/async.js:52:16
    at /home/deployer/cronicle/Cronicle-0.6.11/node_modules/async/lib/async.js:269:32
    at /home/deployer/cronicle/Cronicle-0.6.11/node_modules/async/lib/async.js:44:16
    at /home/deployer/cronicle/Cronicle-0.6.11/node_modules/async/lib/async.js:723:17
    at /home/deployer/cronicle/Cronicle-0.6.11/node_modules/async/lib/async.js:167:37
    at /home/deployer/cronicle/Cronicle-0.6.11/lib/job.js:54:6
    at /home/deployer/cronicle/Cronicle-0.6.11/node_modules/pixl-server-storage/list.js:775:6

Log excerpt from Cronicle.log:
[1491913800.582][2017-04-11 12:30:00][qa-**********com][Cronicle][debug][4][Scheduler Minute Tick: Advancing time up to: 2017/04/11 12:30:00][]
[1491913800.585][2017-04-11 12:30:00][ qa-**********com][Cronicle][debug][4][Auto-launching scheduled item: ej17okjd60x (etl_charging_sessions) for timestamp: Tue, Apr 11, 2017 12:30 PM UTC][]
```

Although I never got reply from the author when asking which server selection algorithm he/she used, I suspect it may be a bug in the Least CPU / Least Memory code.  I found a possible bug in both.

Commit https://github.com/jhuckaby/Cronicle/commit/ca42be4ade1980aa9cffcf4a6c5d655fb277775d should fix this.

\- Joe

**Comment by pallavibatra-cpi** [comment]
Hello joseph,
We were using Least Memory algorithm.
