### ISSUE TITLE
Updated install doesn't run

### ISSUE THREAD

**Issue by geofffox** [jhuckaby/Cronicle#230]
I went to update Cronicle and now it won't start.

[geoff@grads-o-rama cronicle]$ /opt/cronicle/bin/control.sh start
/opt/cronicle/bin/control.sh start: Starting up Cronicle Daemon...
/opt/cronicle/node_modules/pixl-server-web/web_server.js:38
			level: zlib.constants.Z_DEFAULT_COMPRESSION, 
			                     ^

TypeError: Cannot read property 'Z_DEFAULT_COMPRESSION' of undefined
    at Object.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:38:25)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/cronicle/lib/main.js:27:3)
    at Module._compile (module.js:577:32)
/opt/cronicle/bin/control.sh start: Cronicle Daemon could not be started

## Your Setup

Centos7

### Node.js version?

6.17.1

### Are you using a multi-server setup, or just a single server?
single
### Are you using the filesystem as back-end storage, or S3/Couchbase?
files system
### Can you reproduce the crash consistently?
:)

**Comment by jhuckaby** [comment]
Hi there.  Unfortunately you seem to be using Node v6, which has been end-of-life'd (sunset?  I don't know the correct term).  It is no longer even listed on the releases page:

https://nodejs.org/en/about/releases/

Is there any way you can upgrade to Node v8 at least?  Node v10 is actually the current LTS version, but Node v8 is still supported until the end of this year.

I suspect a number of my modules won't work on Node v6 at this point, as I've started to use newer Node.js APIs.

Sorry for the inconvenience.

**Comment by geofffox** [comment]
It says I'm up-to-date?

[geoff@grads-o-rama cronicle]$ sudo yum install nodejs
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ndchost.com
 * epel: mirror.prgmr.com
 * extras: repos-lax.psychz.net
 * nux-dextop: mirror.li.nux.ro
 * updates: mirrors.oit.uci.edu
Package 1:nodejs-6.17.1-1.el7.x86_64 already installed and latest version
Nothing to do

**Comment by jhuckaby** [comment]
Ah, I see you're using `yum`.  Yeah, this is a known issue.  Node.js is rarely ever updated in the main yum repo (not sure why).  You unfortunately have to tell it to use an alternate one:

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages

Which leads to...

https://github.com/nodesource/distributions/blob/master/README.md#rpm

Instructions for latest stable Node v10:

```
curl -sL https://rpm.nodesource.com/setup_10.x | bash -
```

That should instruct `yum` how to find the correct RPM.

**Comment by geofffox** [comment]
I'm thinking this is unexpected

[geoff@grads-o-rama cronicle]$ curl -sL https://rpm.nodesource.com/setup_10.x | bash -

## Installing the NodeSource Node.js 10.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.LS1iatfdZY' 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.LS1iatfdZY'
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
Error executing command, exiting
[geoff@grads-o-rama cronicle]$ 


Is there a way other than yum?  I know only enough to be dangerous -- as demonstrated.

**Comment by jhuckaby** [comment]
Looks like you ran the command as you (your user account).  You have to become root first.  I assume you have `sudo` access on your server?  Try this first:

```
sudo bash
```

Then try that command again inside the root sub-bash:

```
curl -sL https://rpm.nodesource.com/setup_10.x | bash -
```

There are other ways to install Node of course, but honestly, in my opinion `yum` is the best and safest way on Linux RedHat / CentOS / Fedora.

**Comment by geofffox** [comment]
John -- I'm sure we're close and I want you to know I appreciate you giving up your time for me.

[root@grads-o-rama cronicle]# curl -sL https://rpm.nodesource.com/setup_10.x | bash -

## Installing the NodeSource Node.js 10.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.pHgraK4riQ' 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.pHgraK4riQ'

## Cleaning up...

+ rm -f '/tmp/tmp.pHgraK4riQ'

## Checking for existing installations...

+ rpm -qa 'node|npm' | grep -v nodesource

## Your system appears to already have Node.js installed from an alternative source.
Run `sudo yum remove -y nodejs npm` to remove these first.


## Run `sudo yum install -y nodejs` to install Node.js 10.x and npm.
## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
     sudo yum install yarn

**Comment by jhuckaby** [comment]
No problem, and yes, we are close, we just have to remove the old Node.js that is in the way.  Try this:

```
sudo yum remove -y nodejs npm
```

Then try that same command again.

**Comment by geofffox** [comment]
John Huckaby for President!

I owe you a beer or wine or joint or whatever we're doing in Mendocini nowadays.  I can't thank you enough.

I was going to make a feature request, but this seems like a bad time.  Thanks sincerely.

**Comment by jhuckaby** [comment]
Glad it worked!  My name is Joe actually, but close enough 😉 

Feel free to make a feature request whenever!

**Comment by geofffox** [comment]
Oops.  Sorry, Joe.

I make weather maps.

My crons mostly fire off short shell scripts which contain dozens of smaller scripts.  So, when the HRRR model comes in 4xday there will be many scripts to run.  I could add each to Cronicle, but they'd all fire at once.  I wish there was a way to subset entries in much the same way the entries work now.

I know there's the ability to have one script fire off the next, but the maps I make change on a seasonal and sometimes daily basis (tropical).

I hope you understand what I'm getting at.

**Comment by geofffox** [comment]
[sfo-hrrr-sfc.zip](https://github.com/jhuckaby/Cronicle/files/3746215/sfo-hrrr-sfc.zip)

I make stuff like this.  Sorry to zip it, but github doesn't allow mp4s.  It is 1920x1080 HD quality.  I make very pretty weather maps.

**Comment by jhuckaby** [comment]
Oh, wow.  That is an awesome, animated map!  Love it!  Extremely cool!

> My crons mostly fire off short shell scripts which contain dozens of smaller scripts. So, when the HRRR model comes in 4xday there will be many scripts to run. I could add each to Cronicle, but they'd all fire at once. I wish there was a way to subset entries in much the same way the entries work now.

You'll have to forgive me -- I've read this 5 times and I still don't quite get what you are asking.  Can you explain what "subset" means in this context?  Subset the entries?

> I could add each to Cronicle, but they'd all fire at once.

Would they?  I mean, you could schedule them all to fire at different times, or use the [chain reaction](https://github.com/jhuckaby/Cronicle#chain-reaction) system to run them all in sequence.

I'm happy to add new features, I just need to know exactly how they should work.

**Comment by geofffox** [comment]
From time-to-time I need to preface what I say by admitting my last computer class was in the '68-69 semester in high school.  Everything I do is self taught, which means I don't know much less use best practices.  And so my terms aren't always clear.

![xx-76 219 214 36_3012-2019 10 18-22_59_12-066](https://user-images.githubusercontent.com/3851061/67138617-24eb5a80-f1fb-11e9-9e7b-42ce3c94730a.png)

As you (hopefully) can see, I run a busy schedule.  I produce somewhere between 40 and 50k maps daily (On an i5 I bought used).  Many of them are made into animations like the one you saw.

![xx-76 219 214 36_3012-2019 10 18-23_03_10-336](https://user-images.githubusercontent.com/3851061/67138655-988d6780-f1fb-11e9-800a-1796b281deff.png)

The GFS script running now takes 2-2 1/2 hours to run.  It is really running a sequence of commands each producing 120 maps and then creating an animation.  And, as you mentioned those can be chained.  However, on different days or during different seasons some files run/don't run.  Don't I break the chain when I change things, making it cumbersome to do?  That's why I've not tried it.

I guess I'd like to see the chain be a checklist attached to the main entry.

Am I more lucid now?

**Comment by jhuckaby** [comment]
Thanks for the detailed explanation!  I think I understand what you are saying now.  Basically, more flexibility surrounding the chain reaction system, so you can disable individual events or groups, but if those are part of a chain, have it skip over them.  Also, make it more configurable and more visual on the schedule view, so you can easily see where the chains are, and which events link to others.

This is a big feature request, and I can't promise anything (Cronicle is just hobby project), but I will see what I can do for the big v2.0 rewrite.  Thanks again!

That jet stream animation is extremely cool!  Awesome work.  You are a master of your craft 😊

**Comment by geofffox** [comment]
I am hoping all but the geekiest have stopped reading by now.  You are a huge part of my trying to support myself.  So thank you from the bottom of my heart.

I worked at TV stations since 1980, radio since 1969.  I am a meteorologist.  You probably guessed that.  I am the only TV anchor in America who works from home.  I do weather every night across Nebraska from my studio in Southern California. -- 120 hits a week.  Also seven Emmys, four seasons hosting Inside Space on SciFi and dozens on appearances on Good Morning America.

However, my biggest accomplishment might be outliving pancreatic cancer.  Only 9% survive five years.  There is no cure.  But, there's a 1930s operation called a Whipple and if you're lucky and it's found early and then chemo, radiation, chemo, you get to write code at age 69.  

Please consider me the luckiest person you know.

**Comment by jhuckaby** [comment]
Oh, Geoff, it **IS** you!  I thought I recognized your name from somewhere, but I wasn't sure.  You're famous!  Wow, now I'm honored that you chose to use my silly little app!

I just watched your [interview on WTNH](https://www.youtube.com/watch?v=namp-Zfc5hY).  What an awesome home studio you built!  I love the use of the launch pad for switching your settings around (I have one of those too, albeit a [much cheaper one](https://www.amazon.com/gp/product/B004M8YPKM/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)).

Huge congratulations on beating cancer -- and not just any cancer, but the widowmaker itself, pancreatic cancer.  I've never heard of the whipple procedure before.  That sounds absolutely bonkers!  Very happy it worked for you.  I lost my father to prostate cancer in 2017 (it spread to his bones, alas).  But he was 84, and lived a long and happy life.  I hope you do as well!

Well gosh, thank you again for choosing Cronicle, and I will endeavor to add those features you wanted!  I am very honored to be a small part of your weather TV production extravaganza.

Would it be alright if I added you to the small-but-growing [companies using cronicle](https://github.com/jhuckaby/Cronicle#companies-using-cronicle) list?

Have a great weekend Geoff!

\- Joe

**Comment by geofffox** [comment]
Please.  I am in your debt.  If you ever want to do a short Cronicle video let me know.  Stuff like this is what I do and I seriously owe you.  Imagine wrangling all my crons as crons!  It sucked.  

Consider this our "I have a barn, let's put on a show" moment.

**Comment by jhuckaby** [comment]
Oh awesome, that's very generous of you!  I may indeed take you up on that offer, perhaps when I finish the big version 2.0 rewrite.

Cheers!

**Comment by hosnas** [comment]
@jhuckaby when we can expect this version?

**Comment by jhuckaby** [comment]
@hosnas I apologize, but I don't have an ETA on the new version.  I work on Cronicle only as a hobby, on nights and weekends mostly.  I hope to release it by the end of the year, but no promises 😊

**Comment by wanglong167** [comment]
@jhuckaby when we can expect this version?
