### ISSUE TITLE
Use a MinIO S3 Object Store with Let's Encrypt Certificate Authority (issue & resolution)

### ISSUE THREAD

**Issue by daviddpd** [jhuckaby/Cronicle#255]
## Summary

Attempting to use a MinIO Server for S3 storage option with a signed Certificate from Let's Encrypt, will fail with "unable to verify the first certificate".  The setup and debugging for this was not straight forward.  Since the SSL CA is actually getting set  a couple layers deep in Node Modules (I think in aws-cli), it was unclear how to set the CApath.   I initially hacked `aws-sdk/lib/http/node.js` about line 152, and changed  `rejectUnauthorized: true` to `rejectUnauthorized: false`.  But this is not scalable or supportable long term.  Not to mention, bypasses a big security feature of SSL/TLS.

However, ultimately, this can be resolved, with a  one line change.  Going further and to make it clearer to the end user ( Cronicle ops/sysadmins) - would be the addition of another config file.  See "Possible Fixes/Resolutions" below. 

### Cronicle Storage config to use MinIO.
This was also not straight forward 
```
       "Storage": {
                "engine": "S3",
                "AWS": {
                        "endpoint": "https://MINIO.SITE.EXAMPLE.COM:9000",
                        "endpointPrefix": false,
                        "s3ForcePathStyle": true,
                        "region": "EXAMPLECOM",
                        "hostPrefixEnabled": false,
                        "accessKeyId": "cronicle",
                        "secretAccessKey": "*****",
                        "correctClockSkew": true,
                        "maxRetries": 5,
                        "httpOptions": {
                                "connectTimeout": 5000,
                                "timeout": 5000
                        }
                },
                "S3": {
                        "fileExtensions": true,
                        "params": {
                                "Bucket": "cronicle"
                        }
                }
```
I believe `s3ForcePathStyle` stopped prefixing the bucket name to the endpoint.   I don't think region is used in this case.  I'm not sure what `endpointPrefix` does. 

The MinIO server launch (on FreeBSD, but should be the similar on Linux) 
```
/usr/local/bin/minio -C /usr/local/etc/minio -S /usr/local/etc/ssl/corp server --address=:9000  /sr/minio/data1
```
Just for completeness, as MinIO does have pretty documents, but advanced topics are not clearly documented.
For MinIO, the `private.key` and `public.crt` must be named as such (and not way to configure it), and in the top level of the directory specified with `--certs-dir value` or `-S value`.  I made these symlinks.

The  additional CAs for MinIO, have to be in multiple places.  For clusters, they must be in the -`-config-dir`, in `certs/CAs` .. so `${CONFIG_DIR}/certs/CAs/` .  Additionally, I seemed to have issues with symlinks, the CAs must be copies (or possible hard links).    The `minio-client` (FreeBSD) and `mc` (Linux) - must have the CAs at `~/.(minio-client|mc)/certs/CAs/` of the user running the client. 

The LE certificates were installed like this (this is an abridgment of my certificate management script ... and not syntax checked - it allows for cross platform deployment of LE certificates, centrally managed, and auto-updating per machine. ) 
```
SRV="corp"
if [ "${os}" == "FreeBSD" ]; then
        ACMESH="/usr/local/bin/bash /root/.acme.sh/acme.sh"
else 
ACMESH="/root/.acme.sh/acme.sh"
fi
os=`uname`
if [ -n "${sslCertDir}" ]; then
        CERTS="${sslCertDir}"
elif [ "${os}" == "FreeBSD" ]; then
        CERTS="/usr/local/etc/ssl"
elif [ "${os}" == "Linux" ]; then
        CERTS="/etc/ssl/certs"
else
        echo "Error: OS $os/sslCertDir var is unknown" >&2
        exit 2
fi

if [ -n "${CABUNDLE}" ]; then
        echo ${CABUNDLE} | grep  '^/' > /dev/null
        if [ $? -eq 1 ]; then
                if [ "${os}" == "FreeBSD" ]; then
                        CABUNDLE="/etc/ssl/${CABUNDLE}"
                elif [ "${os}" == "Linux" ]; then
                        CABUNDLE="/etc/ssl/certs/${CABUNDLE}"
                fi
        fi
elif [ "${os}" == "FreeBSD" ]; then
        CABUNDLE="/etc/ssl/cert.pem"
elif [ "${os}" == "Linux" ]; then
        CABUNDLE="/etc/ssl/certs/ca-bundle.crt"
else
        echo "Error: OS $os/CABUNDLE var is unknown" >&2
        exit 2
fi
 ${ACMESH} --install-cert -d ${HOST} --cert-file ${CERTS}/${SRV}/cert.pem --key-file ${CERTS}/${SRV}/key.pem --fullchain-file ${CERTS}/${SRV}/chain.pem
 cat ${CABUNDLE} ${CERTS}/${SRV}/chain.pem > ${CERTS}/${SRV}/ca-bundle-chain.pem
ln -s ${CERTS}/${SRV}/key.pem ${CERTS}/${SRV}/private.key
ln -s ${CERTS}/${SRV}/cert.pem ${CERTS}/${SRV}/public.crt
mkdir -p  ${CERTS}/${SRV}/CAs
# minio doesn't like symlink to the chain CA certificate.
cp  /usr/local/etc/ssl/corp/chain.pem /usr/local/etc/ssl/corp/CAs
```

## Your Setup
Pretty much out of the box, except for the storage blob above and LE Certificates.

### Operating system and version? 
CentOS Linux release 7.7.1908 (Core) ( Cronicle ) 
FreeBSD 12.1-STABLE r354267 DPD  ( MinIO )

### Node.js version?
nodejs-12.10.0-1nodesource.x86_64

### Cronicle software version?
Version 0.8.38

### Are you using a multi-server setup, or just a single server?
Single (will be multi- ... still not in "production" yet).

### Are you using the filesystem as back-end storage, or S3/Couchbase?
S3/Minio 
### Can you reproduce the crash consistently?
No crash, won't start because it can't validate the server certificate on the S3/Minio server.

## Log Excerpts
```
> sudo /opt/cronicle/bin/control.sh setup
#!/bin/sh
[1579679079.158][ERROR][s3] Failed to fetch key: global/users: unable to verify the first certificate
[1579679081.444][ERROR][s3] Failed to store object: users/admin: unable to verify the first certificate
/opt/cronicle/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:209:13)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12) {
  message: 'unable to verify the first certificate',
```

## Possible Fixes/Resolutions

One fix was suggested as this :
```
sudo npm config set cafile /etc/ssl/certs/corp/chain.pem 
```
This creates a one-line config in `/root/.npmrc` of `cafile=/etc/ssl/certs/corp/ca-bundle-chain.pem`.

However, this didn't seem work.  NODE itself (not the package manager) needs the CA certificate. 
In `control.sh` there is the `# START CONFIGURATION SECTION  ...`  in which, this is the likely the best place to set:
```
export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/corp/chain.pem
```
It does need to be export'ed - and resolves this issue.

This is still a little hidden and obscure, I'd suggest releasing with the Cronicle, something like, `/opt/cronicle/conf/node-env.sh`, which defaults to just a file of comments, and `control.sh` can source it. 

This will pull this information and configuration into the top level of Cronicle, and a lot easier to find and set.

Sample/Suggestion of` node-env.sh`:
```
#!/bin/sh

# If you need to additional certificates to validate against, for example,
# your S3 storage is a MinIO server with a Let's Encrypt certificate,
# uncomment the next line and set it to the LE "chain.pem" file

# export  NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-bundle.crt 

# Other NODE JS environmental settings that might be useful in rare case.

# NODE_DEBUG                    ','-separated list of core modules that should print debug information
# NODE_DEBUG_NATIVE             ','-separated list of C++ core debug categories that should print debug output
# NODE_DISABLE_COLORS           set to 1 to disable colors in the REPL
# NODE_NO_WARNINGS              set to 1 to silence process warnings
# NODE_OPTIONS                  set CLI options in the environment via a space-separated list
# NODE_PATH                     ':'-separated list of directories prefixed to the module search path
# NODE_PENDING_DEPRECATION      set to 1 to emit pending deprecation warnings
# NODE_PENDING_PIPE_INSTANCES   set the number of pending pipe instance handles on Windows
# NODE_PRESERVE_SYMLINKS        set to 1 to preserve symbolic links when resolving and caching modules
# NODE_REDIRECT_WARNINGS        write warnings to path instead of stderr
# NODE_REPL_HISTORY             path to the persistent REPL history file
# NODE_TLS_REJECT_UNAUTHORIZED  set to 0 to disable TLS certificate validation
# NODE_V8_COVERAGE              directory to output v8 coverage JSON to
# OPENSSL_CONF                  load OpenSSL configuration from file
# SSL_CERT_DIR                  sets OpenSSL's directory of trusted certificates when used in conjunction with --use-openssl-ca
# SSL_CERT_FILE                 sets OpenSSL's trusted certificate file when used in conjunction with --use-openssl-ca
# UV_THREADPOOL_SIZE            sets the number of threads used in libuv's threadpool
```

**Comment by miten5** [comment]
Thanks buddy, its work with vultr object storage also.
