### ISSUE TITLE
API Crash - /api/user/admin_update - when username is null 

### ISSUE THREAD

**Issue by care2DavidDPD** [jhuckaby/Cronicle#257]
## Summary

API Crash - /api/user/admin_update - when username is null 

## Steps to reproduce the problem

This was an accident - I'm developing a php class to provision users/sync users ( since there is no good way to get LDAP integrated  or SSO ).  Definitely a bug in my code as well.

### Operating system and version?

CentOS 7.7

### Node.js version?

node 12

### Cronicle software version?
I had two master, running mis-match versions.
0.8.39
0.8.38

### Are you using a multi-server setup, or just a single server?
multi, 
### Are you using the filesystem as back-end storage, or S3/Couchbase?
MiniOS/S3

### Can you reproduce the crash consistently?

yep, every time username is null. 

## Log Excerpts
```
Tue Jan 28 2020 19:36:49 GMT+0000 (Coordinated Universal Time) - cronicle2.sjc1.care2.com - PID 7524
TypeError: Cannot read property 'username' of null
    at constructor.api_admin_update (/opt/cronicle/node_modules/pixl-server-user/user.js:800:56)
    at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:86:21)
    at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:925:12)
    at constructor.filterHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:795:44)
    at IncomingMessage.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:779:11)
    at IncomingMessage.emit (events.js:214:15)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

=======================
Tue Jan 28 2020 09:03:20 GMT+0000 (Coordinated Universal Time) - cronicle1.sjc1.care2.com - PID 91176
TypeError: Cannot read property 'username' of null
    at constructor.api_create (/opt/cronicle/node_modules/pixl-server-user/user.js:80:53)
    at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:86:21)
    at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:925:12)
    at constructor.filterHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:795:44)
    at IncomingMessage.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/web_server.js:779:11)
    at IncomingMessage.emit (events.js:214:15)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by jhuckaby** [comment]
Thanks, will fix this in the next release!
