### ISSUE TITLE
Cronicle silently crashes after long period of stable ops

### ISSUE THREAD

**Issue by geofffox** [jhuckaby/Cronicle#260]
## Summary
Second crash in past week or two after very long stable run

## Steps to reproduce the problem
clueless

### Operating system and version?
Centos 7

### Node.js version?
10.16.3

### Cronicle software version?
0.8.32

### Are you using a multi-server setup, or just a single server?
single
### Are you using the filesystem as back-end storage, or S3/Couchbase?
back-end
### Can you reproduce the crash consistently?
no

[cronicle-logs.gz](https://github.com/jhuckaby/Cronicle/files/4172967/cronicle-logs.gz)

**Comment by jhuckaby** [comment]
Hey there!  Here is the crash from your logs:

```
Fri Feb 07 2020 12:01:00 GMT-0800 (Pacific Standard Time) - grads-o-rama - PID 2093
TypeError: Cannot read property 'setEncoding' of undefined
    at __construct.init (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:40:17)
    at new __construct (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:31:8)
    at constructor.launchLocalJob (/opt/cronicle/lib/job.js:602:17)
    at /opt/cronicle/lib/job.js:245:11
    at /opt/cronicle/node_modules/async/dist/async.js:3874:9
    at /opt/cronicle/node_modules/async/dist/async.js:473:16
    at replenish (/opt/cronicle/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)
    at /opt/cronicle/node_modules/async/dist/async.js:958:16
    at /opt/cronicle/node_modules/async/dist/async.js:3871:13
```

I've seen this before.  This typically means that your server is completely out of memory, and it cannot spawn the child process to start the job.

It is true that this is a very ungraceful and frankly awful way to handle this error, and I will of course add code to catch this properly and bubble it up in a more sane way, but I think the underlying problem is that something is totally running your server out of memory.

Can you possibly add something to monitor your server memory, and more importantly your process list?

\- Joe

**Comment by jhuckaby** [comment]
More evidence that this may be a server memory issue, also from your logs:

```
[1581105660.224][2020-02-07 12:01:00][grads-o-rama][2093][Cronicle][debug][3][Spawned child process: 0 for job: jk6clhjcvup][bin/shell-plugin.js]
```

Notice that it spawned a child with a PID of `0`.  This is actually not a valid PID, so it looks like the spawn operation did indeed fail, but it didn't throw an error in the expected way (hence the crash).

I will add crash protection for this case, but I am really thinking the root cause is a server memory issue.

**Comment by geofffox** [comment]
The good news is, sitting on the floor right now is a 12 core Xeon server
with 64 Gb ram.  I'm trying to switch over this weekend.

It will replace an i5 with 8 Gb ram.  Just a little step up.  It's weird
this problem should manifest itself now.

Thanks, Joe.

**Comment by geofffox** [comment]
One more thing.  I don't know what I've done to hook up with a dev like
you, but I am very grateful.

With more cores a new strategy for me.  I'll be using a lot of Cronicle.
Thanks again.

**Comment by jhuckaby** [comment]
Haha, sure thing, Geoff, I'm happy to help, and I'm very thankful to have users like you who send me bug reports! 😃 

So, I just released [Cronicle v0.8.40](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.40) which has better error catching for this particular situation.  This will, at the very least, allow the error to be caught and bubbled up properly, and it should not crash Cronicle.  But it won't solve the underlying root cause, which I believe is memory related.  You should be able to upgrade by typing this as root:

```
/opt/cronicle/bin/control.sh upgrade
```

That shiny new 64 GB server of yours sounds like it may also help tho!

If I may shamelessly plug myself for a moment, I do offer another product called [Performa](https://github.com/jhuckaby/performa), which can monitor your server and show you exactly what is causing your memory to run out.  It is totally free and open source like Cronicle is 😊 

One neat feature it has is that it can take a "snapshot" of a server when an alert is triggered.  A snapshot contains a complete list of all running processes, how much CPU & memory they are each taking up, all open TCP sockets, and more.  Also, the default out-of-the-box configuration has an alert configured for 95% memory usage (i.e. only 5% of memory available), and this triggers a snapshot.  So if you had this running, it could probably tell you exactly which process is your memory hog.

Thanks again, and good luck!

**Comment by geofffox** [comment]
0.8.40 is in.

The 'new' server is only new to me.  I am attempting to start a business.
I think I told you, I'm a meteorologist.  I have a full control room and
studio and produce around 40,000 weather maps a day.

The server itself is a head scratcher.  It's not new by any means but 2x
XEON 6 core cpus, 64 Gb, 8 Tb SAS, 2 gigabit Ethernet ports for < $300
delivered!  How could I not?

**Comment by geofffox** [comment]
Now that I've gotten bitten by the 1Gb memory limit (fixed), I've gone back
and read the docs.  Well, as much as I understand.

This is an amazing undertaking and as someone who often eschews
documentation, astoundingly complete.

QUESTION:  I am totally cloning the structure of the old server on the new
one.  Is there a way to export/import my schedule?

Also installed Performa.  I'll admit it.  I'm attracted to charts, graphs
and numbers long before I totally get their significance.

**Comment by geofffox** [comment]
The migration has begun.  I did figure out how to move my schedules from one machine to the other, but before I did it realized it wouldn't work with my new flow anyway,  

But, that does bring up an unforeseen problem.  Four times a day I get computer model data.  Once that's in somewhere between 30-50 scripts fire off.  In the past I had them go one-after-another by executing a single BASH script with each on a line.  With all these cores I'm going to fire them more rapidly (All at once?  I am clueless).  But they need to wait for the data acquisition to finish.

I know a finished script can call another script.  I'd like to call many scripts or a group or whatever is easiest on the completion of the data gathering.

I hope I'm making sense.  Can this be done?

Also, am enjoying Performa though this machine isn't really working yet.

**Comment by jhuckaby** [comment]
Hey Geoff,

Yup, you told me!  Your studio looks awesome, and I love your custom weather maps.  I'm very happy that my software plays a small part in your setup!

Okay, so Cronicle of course supports running multiple jobs in parallel, but your specific use case isn't covered very well.  Cronicle does have "chain reactions", where one job completes (like your model data ingest), and then that fires off another job (your big shell script).  That's easy, but the problem is, currently a chain reaction can only fire off one single job.  It can't spawn a bunch in parallel.  This is something I'm addressing in the next major release, which is more of a complete rewrite to be honest, so it's several months off at least 😞 

In the meantime, however, you have several options to make this work.  First, you can use a Linux trick where a shell script is launched in the background, by adding ` &` to the end of the command.  This allows you to fire off multiple scripts in parallel.  But obviously you don't want all 50 of your scripts to run at once -- that might kill the server.  So you could, for example, split up your 50 scripts into, let's say 5 chunks, each running 10 scripts in series, and all 5 chunks could run in parallel.

So imagine something like this: `batch-A.sh` would fire off `job-1.sh`, `job-2.sh`, `job-3.sh` all the way to `job-10.sh`.  Then `batch-B.sh` would fire off `job-11.sh`, `job-12.sh` all the way to `job-20.sh`.  You get the idea -- repeat this all the way to `batch-E.sh` firing off `job-41.sh` and ending with `job-50.sh`.  Then, finally, you write one master script (which Cronicle would initiate) which fires off all 5 batch scripts using the `&` trick on each, like this:

```sh
#!/bin/bash

/home/geofffox/scripts/batch-A.sh &
/home/geofffox/scripts/batch-B.sh &
/home/geofffox/scripts/batch-C.sh &
/home/geofffox/scripts/batch-D.sh &
/home/geofffox/scripts/batch-E.sh &
```

When this one master script runs, it will execute `batch-A.sh`, `batch-B.sh`, `batch-C.sh`, `batch-D.sh`, and `batch-E.sh`, all in parallel.  And each of those scripts run their respective 10-or-so scripts in series.  This way you have more control over the amount of concurrent scripts running at once.  This example would use around 5 CPU cores, give or take.

The downside of this method is that all the scripts will run in the background, and Cronicle has no real way of keeping track of them, showing you progress, or any of that fun stuff.  They'll just kinda run "headless" and unmanaged.

Another way you could do this is by using the **[Cronicle REST API](https://github.com/jhuckaby/Cronicle#json-rest-api)**, and the command-line `curl` utility that ships with most Linux distros.  With this method, you can actually spawn multiple jobs in parallel simply by sending API calls.

For this to work I am assuming you're running Cronicle on a single server, not a cluster of servers (the latter makes this much more complicated).  So first, create an **[API Key](https://github.com/jhuckaby/Cronicle#api-keys)** for your scripts to use.  Your API key will look something like this: `0095f5b664b93304d5f8b1a61df605fb`.

Also, make sure your server actually has `curl` by typing `which curl` into the terminal.  If not, you can install it via `yum install curl` for RedHat/Fedora/CentOS, or `apt-get install curl` for Debian/Ubuntu.

What we're going to do here is use Cronicle's **[run_event](https://github.com/jhuckaby/Cronicle#run_event)** API to trigger multiple jobs to run at once.  What you should do is split up your 50 scripts into batches (similar to the previously described method above), and create 5 different Cronicle Events, each that run 10 or so of your scripts in series.

Once you have all that, all you need is to add these commands to the end of your model data shell script, when it is time to fire off your other 50 jobs:

```sh
# Data model import completed, about to fire off scripts...

curl -s "http://localhost:3012/api/app/run_event/v1?api_key=YOUR_API_KEY_HERE&title=Batch-A"
curl -s "http://localhost:3012/api/app/run_event/v1?api_key=YOUR_API_KEY_HERE&title=Batch-B"
curl -s "http://localhost:3012/api/app/run_event/v1?api_key=YOUR_API_KEY_HERE&title=Batch-C"
curl -s "http://localhost:3012/api/app/run_event/v1?api_key=YOUR_API_KEY_HERE&title=Batch-D"
curl -s "http://localhost:3012/api/app/run_event/v1?api_key=YOUR_API_KEY_HERE&title=Batch-E"
```

Obviously, replace all the occurrences of `YOUR_API_KEY_HERE` with your actual API Key that you generated above.  Oh, this also assumes that you're running Cronicle on the default port of `3012`.  If you changed this in your configuration file, please also change the commands above.

These 5 commands will fire off events from your schedule named `Batch-A`, `Batch-B`, `Batch-C`, `Batch-D`, and `Batch-E`, all in parallel.  The assumption is that you'll create each of these events to run 10 or so scripts each, but all 5 batches will run in parallel.

You can change the ratio of number of batches vs. number of scripts in each batch, to adjust the concurrency -- as in, how many of your server CPU cores you want to burn up.

The downside of this method is that it is more complicated to setup and get going.  The upside is that all these batch jobs will be fully managed and controlled by Cronicle, so you can keep track of them as they run, see progress, completion, console output, etc.

Another neat trick you can do with Cronicle is send progress updates by simply echoing `25%` , `50%`, `75%`, and so on, to the console, between each of your shell script commands.  This automatically updates the Cronicle job progress bar, and provides you with an estimated time remaining, etc.

So for example, let's say you are putting the first 10 scripts into `Batch-A`.  If you did it like this...

```sh
#!/bin/bash

/home/geofffox/scripts/job-1.sh
echo "10%"

/home/geofffox/scripts/job-2.sh
echo "20%"

/home/geofffox/scripts/job-3.sh
echo "30%"

/home/geofffox/scripts/job-4.sh
echo "40%"

/home/geofffox/scripts/job-5.sh
echo "50%"

/home/geofffox/scripts/job-6.sh
echo "60%"

/home/geofffox/scripts/job-7.sh
echo "70%"

/home/geofffox/scripts/job-8.sh
echo "80%"

/home/geofffox/scripts/job-9.sh
echo "90%"

/home/geofffox/scripts/job-10.sh
echo "100%"
```

So this way, when each sub-script completes, it prints out a percentage of the total job completed. Cronicle automatically detects this in the output stream, and updates its own progress bar and time remaining.

Anyway, I hope this was helpful to you.  I'll let you know when the big rewrite of Cronicle is released, which has full support for spawning multiple events in parallel for a chain reaction.

Have a great weekend!

**Comment by geofffox** [comment]
Absolutely, positively.  Incredibly helpful.  I had been considering
something just like your first suggestion.

As it is right now I don't have granular feedback because one script
triggered by Cronicle might run a few dozen smaller scripts.  So that's
less of a shock/problem.

My wife and I have to meet some friends in LA for dinner (1.5 - 2 hours
away), so this will probably get started late tonight or tomorrow.

If you're ever in SoCal please come see my setup and let me take you to
dinner.  Please consider this a legit offer.  I sincerely value you work.

**Comment by jhuckaby** [comment]
Haha, thank you for the invite!  I rarely ever get down to SoCal anymore (I live up way north of SF), but I will definitely ping you if I ever do!  Cheers!
