### ISSUE TITLE
After upgrade: [Uncaught Exception: TypeError: Cannot read property 'username' of undefined]

### ISSUE THREAD

**Issue by fullmoon4465** [jhuckaby/Cronicle#267]
# Summary
Ran upgrade and now it won't start back up without debugging. Using couchbase as backend

### Node.js version?

v10.19.0

### Cronicle software version?

Upgrading Cronicle from v0.8.31 to v0.8.45

### Are you using a multi-server setup, or just a single server?

Multi. I've only attempted on 2 of the 5 in the cluster and noticed process wasn't starting back up after upgrade.

### Are you using the filesystem as back-end storage, or S3/Couchbase?
Couchbase

### Can you reproduce the crash consistently?
Yes

## Log Excerpts

[Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'username' of undefined][TypeError: Cannot read property 'username' of undefined     at new Cluster (/opt/cronicle/node_modules/couchbase/lib/cluster.js:26:25)     at constructor.setup (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:47:18)     at constructor.startup (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:33:8)     at constructor.startup (/opt/cronicle/node_modules/pixl-server-storage/storage.js:109:15)     at /opt/cronicle/node_modules/pixl-server/server.js:402:10     at /opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:3110:16     at replenish (/opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:1011:17)     at /opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:1016:9     at eachLimit$1 (/opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:3196:24)     at Object.<anonymous> (/opt/cronicle/node_modules/pixl-server/node_modules/async/dist/async.js:1046:16)]

**Comment by jhuckaby** [comment]
This looks like an issue with the Couchbase NPM module, not Cronicle per se.  Can you try downgrading back to Cronicle v0.8.31 and see if the problem goes away?  I ask because I haven't made any changes to the storage layer since September of last year.  I suspect the downgrade will not make any difference, and the problem will persist.

Is it possible that your Couchbase NPM module got updated?  Cronicle's upgrade script does call `npm update` so that probably upgraded your Couchbase module.  I think they've made breaking changes (*shakes fist at Couchbase*).

You might need to force-downgrade your Couchbase module, to whatever version you had before.  You mentioned that you have multiple servers, some still in working condition.  If you could, please check which version they have, with:

```
grep version /opt/cronicle/node_modules/couchbase/package.json
```

Compare this to your upgraded server that is not working.  If the versions differ, you may need to force downgrade your Couchbase on the broke boxes, back to the working version.  Example:

```
cd /opt/cronicle
npm install couchbase@2.6.6
```

Good luck, and sorry!

**Comment by fullmoon4465** [comment]
After the upgrade the module was "missing" so i had to install couchbase again. Make sense

Running hosts:  "version": "2.6.8"
2 upgraded hosts: "version": "3.0.0"

Downgraded to 2.6.8 via npm and cronicle is running again on this upgraded host.
