### ISSUE TITLE
List page could not be loaded: global/schedule/-6: Error: Failed to fetch key: global/schedule/-6: File not found

### ISSUE THREAD

**Issue by Daido** [jhuckaby/Cronicle#303]
First of all, thanks for this great software!

## Summary

The `cronicle` started failing with the following error `List page could not be loaded: global/schedule/-6: Error: Failed to fetch key: global/schedule/-6: File not found`

## Setup

Docker image `intelliops/cronicle:0.8.28`.
https://hub.docker.com/r/intelliops/cronicle

### Are you using the filesystem as back-end storage, or S3/Couchbase?
filesystem

there is space available

### Can you reproduce the crash consistently?
yes

## Log Excerpts

`[1593517007.33][2020-06-30 11:36:47][cronicle-server-primary-0][7][Filesystem][debug][9][JSON fetch complete: global/schedule][]
 [1593517007.33][2020-06-30 11:36:47][cronicle-server-primary-0][7][Storage][transaction][get][global/schedule][{"elapsed_ms":2.845}]
 [1593517007.33][2020-06-30 11:36:47][cronicle-server-primary-0][7][Storage][debug][9][Loading list page: global/schedule/-6][]
 [1593517007.33][2020-06-30 11:36:47][cronicle-server-primary-0][7][Filesystem][debug][9][Fetching Object: global/schedule/-6][/opt/cronicle/data/global/2a/bb/c1/2abbc18a1d80730537b1335fa06840ed.json]
 [1593517007.331][2020-06-30 11:36:47][cronicle-server-primary-0][7][Storage][debug][9][List page could not be loaded: global/schedule/-6: Error: Failed to fetch key: global/schedule/-6: File not found][]
 [1593517007.331][2020-06-30 11:36:47][cronicle-server-primary-0][7][Storage][debug][9][Removing reader from shared lock: |global/schedule][{"readers":0}]
 [1593517007.331][2020-06-30 11:36:47][cronicle-server-primary-0][7][Storage][debug][9][Unlocking key: |global/schedule (0 clients waiting)][]
 [1593517007.332][2020-06-30 11:36:47][cronicle-server-primary-0][7][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'length' of null][TypeError: Cannot read property 'length' of null     at /opt/cronicle/lib/scheduler.js:31:35     at /opt/cronicle/node_modules/pixl-server-storage/list.js:503:12     at /opt/cronicle/node_modules/async/dist/async.js:3874:9     at /opt/cronicle/node_modules/async/dist/async.js:473:16     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:976:17)     at /opt/cronicle/node_modules/async/dist/async.js:958:16     at /opt/cronicle/node_modules/async/dist/async.js:3871:13     at /opt/cronicle/node_modules/pixl-server-storage/list.js:495:6     at /opt/cronicle/node_modules/pixl-server-storage/list.js:95:5     at /opt/cronicle/node_modules/pixl-server-storage/storage.js:348:20]
 [1593517007.333][2020-06-30 11:36:47][cronicle-server-primary-0][7][Error][error][crash][Emergency Shutdown: TypeError: Cannot read property 'length' of null][]
 [1593517007.334][2020-06-30 11:36:47][cronicle-server-primary-0][7][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read property 'length' of null][]
 TypeError: Cannot read property 'length' of null
     at /opt/cronicle/lib/scheduler.js:31:35
     at /opt/cronicle/node_modules/pixl-server-storage/list.js:503:12
     at /opt/cronicle/node_modules/async/dist/async.js:3874:9
     at /opt/cronicle/node_modules/async/dist/async.js:473:16
     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:976:17)
     at /opt/cronicle/node_modules/async/dist/async.js:958:16
     at /opt/cronicle/node_modules/async/dist/async.js:3871:13
     at /opt/cronicle/node_modules/pixl-server-storage/list.js:495:6
     at /opt/cronicle/node_modules/pixl-server-storage/list.js:95:5
     at /opt/cronicle/node_modules/pixl-server-storage/storage.js:348:20`

**Comment by Daido** [comment]
I analyzed the logs in a few days and found useful information:

`[1592993160.814][2020-06-24 10:06:00][cronicle-server-primary-0][9][Error][error][state][Failed to update state: Error: Failed to write file: global/state: /opt/cronicle/data/_temp/d336e75083d08c96b2e4bba57227c4e8.json.tmp.910: ENOSPC: no space left on device, open '/opt/cronicle/data/_temp/d336e75083d08c96b2e4bba57227c4e8.json.tmp.910'][]`

I think that after the `pod` was rebooted, the temporary data was deleted, and now there is space on the device.

But it seems that the state is not consistent and the `cronicle` cannot start.
Are there any recommendations on how to fix the data manually?

**Comment by jhuckaby** [comment]
Hey there,

Well, this is not a great situation, because if the primary storage runs out of space (filesystem in your case), then Cronicle will indeed end up with corrupted records.  There is no easy way to recover from this, unless you have [backups you can restore](https://github.com/jhuckaby/Cronicle#data-import-and-export) to.  Assuming you do not have this, then you have two options.  You can just wipe all the data in `/opt/cronicle/data/*` and start fresh, or you can **attempt** to manually recover the damaged records.  I do not recommend or support the latter, but I will tell you how to use the CLI.  It's very low level and thus not documented.

Assuming that only page `-6` of your schedule is missing (going by your log excerpt above), and the rest of the schedule pages and other records are in tact, then you may be able to manually "shrink" the schedule list to only 6 pages (the page numbers are zero-based).  However, this is a huge "if".  There may be other corruption that isn't captured in your log excerpt.

First, **stop Cronicle** so you are not manipulating data while it is running (this will surely destroy it).  Then use this command to see what the schedule thinks about itself:

```
cd /opt/cronicle
bin/control.sh stop
bin/storage-cli.js get global/schedule
```

The output should look something like this (but with different values of course):

```js
{
	"page_size": 50,
	"first_page": 0,
	"last_page": -6,
	"length": 350,
	"type": "list"
}
```

This shows you how large Cronicle thinks the schedule list is, and the first and last page numbers (zero-based).  You can fetch each page by using this syntax:

```
bin/storage-cli.js get global/schedule/0
bin/storage-cli.js get global/schedule/-1
bin/storage-cli.js get global/schedule/-2
bin/storage-cli.js get global/schedule/-3
bin/storage-cli.js get global/schedule/-4
bin/storage-cli.js get global/schedule/-5
bin/storage-cli.js get global/schedule/-6
```

Try to fetch all 7 pages (0-based), and see if only the final `global/schedule/-6` get fails.  If all the other pages are indeed in tact and look correct to you, then you can trim the list by manipulating the header record.

To do this, we'll be using the `edit` command, which will launch your local Terminal editor (usually `vi` or `vim`).  Make sure you are familiar with this, and that your desired editor is set as the `EDITOR` environment variable in your shell.  Then, run this command which will spawn the editor:

```
bin/storage-cli.js edit global/schedule
```

You should now be "editing" the `global/schedule` record in your editor.  The data is in JSON format.  Please be very careful with the syntax, as it is highly sensitive.  What you need to do here is make two edits.  First, change the `last_page` from `-6` to `-5`, making it forget the last page ever existed.  Then, change the `length` to compensate for the loss.  This is the tricky bit.  I am making the rather large assumption that all the other pages are "full" (have 50 items each), in which case the `length` should be set to `300`.  Try making those two edits, then save and exit your editor.  You actually have to save for the CLI command to detect and store the record back into storage.

Then, try starting Cronicle again and see if it is happy.

If not, then you probably will have to wipe your data and start fresh.  You can try to [generate a data export](https://github.com/jhuckaby/Cronicle#data-import-and-export) before doing this, but if there is indeed list corruption then this command will likely fail as well.

The next major version of Cronicle (v2.0) will have a much more robust "database" layer with ACID-like transactions and rollbacks on underlying filesystem errors, so this kind of thing *should never happen*.  I apologize that it happened to you.  Cronicle is a one-man open source effort, and I couldn't foresee all the possible issues in v1.0.

Good luck.

\- Joe

**Comment by Daido** [comment]
Thanks for your reply. Since I got this error in the development environment, I wiped the data. But in any case, this information will be useful to everyone who encounters this problem in the production environment.
