### ISSUE TITLE
Crash uploading logs

### ISSUE THREAD

**Issue by fl4p** [jhuckaby/Cronicle#348]
Cronicle crashes at startup:
```
RangeError: Maximum call stack size exceeded
    at Encoder.encode (/opt/cronicle/node_modules/socket.io-parser/index.js:133:20)
    at Client.packet (/opt/cronicle/node_modules/socket.io/lib/client.js:156:20)
    at Socket.packet (/opt/cronicle/node_modules/socket.io/lib/socket.js:223:15)
    at Socket.emit (/opt/cronicle/node_modules/socket.io/lib/socket.js:168:12)
    at constructor.masterSocketEmit (/opt/cronicle/lib/engine.js:325:12)
    at constructor.uploadJobLog (/opt/cronicle/lib/job.js:1201:32)
    at /opt/cronicle/lib/engine.js:764:14
    at /opt/cronicle/node_modules/async/dist/async.js:3096:16
    at replenish (/opt/cronicle/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)
```

I can delete the contents of the logs folder to fix temporarily fix this, but the error will occur after 1 week or so.

Version 0.8.50

**Comment by mikeTWC1984** [comment]
Just curious, are you running it on some vm with limited resources, like droplet/raspberry pi, and how many jobs are running
