### ISSUE TITLE
Can Cronicle run python script

### ISSUE THREAD

**Issue by mauriziozito01** [jhuckaby/Cronicle#360]
i would like to schedule python scripts but i didn't understand how to do it.

thanks

Maurizio

**Comment by mikeTWC1984** [comment]
![image](https://user-images.githubusercontent.com/31977106/101295400-7550bd80-37eb-11eb-879a-2243e35fa57a.png)

**Comment by mauriziozito01** [comment]
Permission denied

not work

**Comment by mauriziozito01** [comment]
![image](https://user-images.githubusercontent.com/75208171/101404287-bd98da00-38d6-11eb-9db9-74e7a30a2afa.png)

**Comment by mikeTWC1984** [comment]
I guess you started cronicle as non-root user or plugin is running as non-root user.

**Comment by mauriziozito01** [comment]
cronicle was started as docker
I am using a synology nas as a server

thanks

**Comment by mikeTWC1984** [comment]
yes, that's the gotcha of docker if running as non-root. If you start cronicle inside docker as user with id 123, you should also have user with same uid on the host, and grant him write access on volumes you use. You should take care of it in docker file. 
I think it might be a better idea to run cronicle as root and run shell-plugin as non-root. It's actually more secure, since you can control access to all your files/storage.

**Comment by mauriziozito01** [comment]
i am not very experienced
Honestly, I launch docker from the application and I don't know which user it is running with.
I know you can tell him to run with elevated privileges.
I honestly have no idea how to implement what you told me.
where do i find a guide to help me understand?

**Comment by mauriziozito01** [comment]
Docker run on synology as root
but i receive this error
Error: Script failed: Permission denied (spawn /tmp/cronicle-script-temp-jkift5f2s04.sh EACCES)

**Comment by mauriziozito01** [comment]
i try this change:
![image](https://user-images.githubusercontent.com/75208171/101469198-b7d9dd80-3944-11eb-92ca-29756f555722.png)
but cronicle stop work
![image](https://user-images.githubusercontent.com/75208171/101469264-d213bb80-3944-11eb-955f-a94494cfc75b.png)

**Comment by mikeTWC1984** [comment]
You seem to use some old image, newer version of cronicle shouldn't crash on plugin error.

**Comment by mauriziozito01** [comment]
new error

![image](https://user-images.githubusercontent.com/75208171/101541842-3b75e780-39a2-11eb-929e-5580e7ef1919.png)

I have read that it may be a memory issue, but my system has no memory issues right now

**Comment by mauriziozito01** [comment]
![image](https://user-images.githubusercontent.com/75208171/101542696-70366e80-39a3-11eb-9c4d-544beaec3eba.png)

**Comment by mikeTWC1984** [comment]
can you just run some simple  bash command like
```bash
#!/bin/bash

echo 123
```

**Comment by mikeTWC1984** [comment]
what image or dockerfile are you using?

**Comment by mauriziozito01** [comment]
![image](https://user-images.githubusercontent.com/75208171/101543726-e7b8cd80-39a4-11eb-801b-2c17368bc518.png)

**Comment by mauriziozito01** [comment]
sorry
# Job ID: jkighyatz04
# Event Title: test
# Hostname: localhost
# Date/Time: 2020/12/08 21:29:36 (GMT+0)

123

# Job completed successfully at 2020/12/08 21:29:36 (GMT+0).
# End of log.

**Comment by mauriziozito01** [comment]
is it a python error?

**Comment by mikeTWC1984** [comment]
I think it just can't digest output of your python script. Are you printing out some json stuff?

**Comment by mauriziozito01** [comment]
print('prova')

it is a test. 
i wanted to test if python ran

**Comment by mauriziozito01** [comment]
![image](https://user-images.githubusercontent.com/75208171/101545037-f0120800-39a6-11eb-8e62-adce01d0d735.png)

**Comment by mikeTWC1984** [comment]
your shebang doesnt look right, try 
```#!/usr/bin/env python```

**Comment by mauriziozito01** [comment]
# Job ID: jkigixk1v08
# Event Title: test
# Hostname: localhost
# Date/Time: 2020/12/08 21:57:01 (GMT+0)

env: can't execute 'python2.7': No such file or directory

# Job failed at 2020/12/08 21:57:01 (GMT+0).
# Error 127: Script exited with code: 127: env: can't execute 'python2.7': No such file or directory
# End of log.

**Comment by mauriziozito01** [comment]
on synology i believe python gets installed in a different place

**Comment by mikeTWC1984** [comment]
you need to specify full path to python executable if it's not installed. e.g.:
```#!/usr/bin/python```
if it's installed then this should work
```#!/usr/bin/env python```
Anyway, this is not a cronicle issue. I'd suggest to close this issue and google for shebang for more examples if needed

**Comment by mauriziozito01** [comment]
I make a summary because in my opinion we are talking about 2 different problems

I now use the synology scheduler which is similar to yours in the way of launching jobs
this is an example:
![image](https://user-images.githubusercontent.com/75208171/101614287-0f438080-3a0d-11eb-99a0-e1dac232eef4.png)

But this scheduler is very limited and I wanted to replace it.

I have tried in every way to laciare sql script with all possible paths indicated but it always gives me this error

# Job failed at 2020/12/09 09:44:17 (GMT+0).
# Error: Script failed: No such file or directory (spawn /tmp/cronicle-script-temp-jkih873zb0q.sh ENOENT)
# End of log.

But when I launch it copsi gives me this error

/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:40
		this.streamIn.setEncoding('utf8');
		              ^

TypeError: Cannot read property 'setEncoding' of undefined
    at __construct.init (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:40:17)
    at new __construct (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:31:8)
    at __construct.<anonymous> (/opt/cronicle/bin/shell-plugin.js:32:16)
    at __construct.emit (events.js:182:13)
    at Socket.<anonymous> (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:75:12)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

# Job failed at 2020/12/09 09:44:38 (GMT+0).
# Error: Child 1049 crashed with code: 1
# End of log.

So here I manage to run the script but an exception is thrown.
This exception is a cronicle issue.
Except that you have focused on the path which in my opinion has nothing to do with it.
Because when the path is wrong it gives me another error.

with synology I had errors with encoding for some scripts in fact in some cases I had to add this wording at the top of the script
# coding = utf-8

can it be the same problem?

the error is a problem in a chronicle module

my version of cronicle is 8.45 thinks it is too old.
I can't find a docker with a more updated version
thanks

Maurizio

**Comment by mauriziozito01** [comment]
i downloaded version 0.52
now my mistake is still different

# Job ID: jkihfeyl802
# Event Title: test
# Hostname: localhost
# Date/Time: 2020/12/09 14:06:21 (GMT+1)

internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:503:9)
    at __construct.<anonymous> (/opt/cronicle/bin/shell-plugin.js:25:17)
    at emitOne (events.js:116:13)
    at __construct.emit (events.js:211:7)
    at Socket.<anonymous> (/opt/cronicle/node_modules/pixl-json-stream/json-stream.js:75:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)

# Job failed at 2020/12/09 14:06:22 (GMT+1).
# Error: Child 256 crashed with code: 1
# End of log.

**Comment by mikeTWC1984** [comment]
That's permission error. I'm confused about your environment, what image or docker file are you using?

**Comment by mauriziozito01** [comment]
https://registry.hub.docker.com/r/btdwv/cronicle/

**Comment by mikeTWC1984** [comment]
I tried this image, this works:
```
#!/usr/bin/env python3

print("hello")
```
I see it runs as root by default, so you shouldn't have any problems with accessing volumes

**Comment by mauriziozito01** [comment]
I launched the container with the command: docker run -u root
The container also provides to indicate:
PUID and PGID
I have set it with the data of the root user
I also tried using my admin user data
But I always have the same error
to which folders should I assign special permissions?

**Comment by mikeTWC1984** [comment]
This image runs as root by default. No need to specify anything else. Are you getting error if running "hello world" script,  or if you touching files on your volumes?

**Comment by mauriziozito01** [comment]
no only if I try to run a python but without touching files.
Or rather I don't know if chronicle touches some files but my script only makes a print
