### ISSUE TITLE
Cannot find module when running shell script

### ISSUE THREAD

**Issue by jcfbeardsley** [jhuckaby/Cronicle#365]
## Summary
When running Cronicle as a slave system, there seems to be a repeatable crash when trying to use the shell script plugin when using Ubuntu 20.04 LTS and Node v12 (12.20.0). Master server is running Ubuntu 18.04 LTS with Node v12 and the shell plugin executes successfully, as does running on another slave with Ubuntu 18.04 LTS with Node v12. Indications are that there is an issue with pixl-json-stream not being present on the system, however `npm -g list | grep pixl` on the slave machine shows that it is:

```
├── pixl-class@1.0.3
└─┬ pixl-json-stream@1.0.6
  └── pixl-class@1.0.3
```

## Steps to reproduce the problem
Setup master and slave with versions as described above, then try running a shell script from the pre-defined plugin on the slave system.

### Operating system and version?
Ubuntu 20.04 LTS (Slave system), Ubuntu 18.04 LTS (Master)

### Node.js version?
12.20.0

### Cronicle software version?
0.8.46

### Are you using a multi-server setup, or just a single server?
Multi-server. Crash occurs on the slave system.

### Are you using the filesystem as back-end storage, or S3/Couchbase?
No

### Can you reproduce the crash consistently?
Yes

## Log Excerpts
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'pixl-json-stream'
Require stack:
- /opt/cronicle/bin/shell-plugin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/cronicle/bin/shell-plugin.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/cronicle/bin/shell-plugin.js' ]
}
```

**Comment by mikeTWC1984** [comment]
Did you see this one?
https://github.com/jhuckaby/Cronicle/issues/361
Might be some 20.04 thing. Also try some common suggestion regarding internal/modules/cjs/loader.js error, I'd doubt this is something cronicle specific.
