### ISSUE TITLE
Zlib error: unexpected end of file

### ISSUE THREAD

**Issue by asyslinux** [jhuckaby/Cronicle#405]
## Summary

This error cause a shutdown  of primary node:

Cronicle.log:

[1621157404.504][2021-05-16 05:30:04][hostname][43741][Cronicle][debug][1][Uncaught Exception: Error: unexpected end of file][Error: unexpected end of file     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)]
[1621157404.504][2021-05-16 05:30:04][hostname][43741][Cronicle][debug][1][Emergency Shutdown: Error: unexpected end of file][]

## Steps to reproduce the problem

Need a big setup with 50+ cronicle worker servers in internet with unstable connections some times and with many cron tasks >250).

This is a vary rare error. On my setup i look this error around 1-2 times per month. Not more.

### Operating system and version?

Debian 9.x 64 bit

### Node.js version?

v12.20.0

### Cronicle software version?

0.8.54

### Are you using a multi-server setup, or just a single server?

Multi

### Can you reproduce the crash consistently?

1-2 times per month on my big setup

## Log Excerpts

Cronicle.log:

[1621157404.504][2021-05-16 05:30:04][hostname][43741][Cronicle][debug][1][Uncaught Exception: Error: unexpected end of file][Error: unexpected end of file     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)]
[1621157404.504][2021-05-16 05:30:04][hostname][43741][Cronicle][debug][1][Emergency Shutdown: Error: unexpected end of file][]

Error.log:

[1621157404.502][2021-05-16 05:30:04][hostname][43741][Error][error][job][Failed to fetch job log file: http://remotehostname:3200/api/app/fetch_delete_job_log?path=%2Fopt%2Fcronicle%2Flogs%2Fjobs%2Fjkoqz9bxq68.log&auth=ef26678134e95531d6d667e9426eb9a70057b94d7e049af1af2d238a664e4115: Error: Connection reset by peer (read ECONNRESET)][]
[1621157404.504][2021-05-16 05:30:04][hostname][43741][Error][error][crash][Emergency Shutdown: Error: unexpected end
of file][]

crash.log:

Sun May 16 2021 05:30:04 GMT-0400 (Eastern Daylight Time) - hostname - PID 43741
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)

**Comment by jhuckaby** [comment]
Fixed in [v0.8.59](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.59).  Thanks!
