### ISSUE TITLE
unexpected token a in JSON

### ISSUE THREAD

**Issue by nreith** [jhuckaby/Cronicle#419]
## Steps to reproduce the problem

Follow install instructions in README.md version 0.8.62, 61, or 60.
Haven't tried further back

## Your Setup

Ubuntu 20.04 with nodejs and npm

### Operating system and version?

Ubuntu 20.04

### Node.js version?

10.19.0

### Cronicle software version?

see above

### Are you using a multi-server setup, or just a single server?

No

### Are you using the filesystem as back-end storage, or S3/Couchbase?

No

### Can you reproduce the crash consistently?

Yes

## Log Excerpts

sudo /opt/cronicle/bin/control.sh setup
internal/modules/cjs/loader.js:800
    throw err;
    ^

SyntaxError: /opt/cronicle/conf/config.json: Unexpected token a in JSON at position 59
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:797:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/cronicle/bin/storage-cli.js:22:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by jhuckaby** [comment]
It sounds like you have a typo in your configuration file.  Can you upload the file here?

This file → `/opt/cronicle/conf/config.json`

**Comment by nreith** [comment]
Yes. Apologies, I mucked it with sed -i. Fixed now. Thanks for taking the time to look.
