### ISSUE TITLE
Using couchbase - during control.sh setup I get: TypeError: this.cluster.authenticate is not a function

### ISSUE THREAD

**Issue by jaedaen** [jhuckaby/Cronicle#448]
## Summary

During setup I get a node stacktrace saying TypeError: this.cluster.authenticate is not a function

## Steps to reproduce the problem

curl -s https://raw.githubusercontent.com/jhuckaby/Cronicle/master/bin/install.js | node
cd /opt/cronicle
npm install couchbase

Change storage in /opt/cronicle/conf/config.json to be:

        "Storage": {
                "engine": "Couchbase",
                "Couchbase": {
                        "connectString": "couchbase://127.0.0.1",
                        "bucket": "cronicle",
                        "username": "cronicle",
                        "password": "mypassword",
                        "serialize": false,
                        "keyPrefix": "cronicle" 
                }
        },

/opt/cronicle/bin/control.sh setup

output:

/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:51
			this.cluster.authenticate(this.config.get('username'), this.config.get('password'));
			             ^

TypeError: this.cluster.authenticate is not a function
    at constructor.setup (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:51:17)
    at constructor.startup (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:33:8)
    at __construct.startup (/opt/cronicle/node_modules/pixl-server-storage/storage.js:109:15)
    at /opt/cronicle/node_modules/pixl-server-storage/standalone.js:50:19
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

## Your Setup

npm package versions:

 npm list | grep storage
├─┬ pixl-server-storage@2.0.10
npm list | grep couchbase
├─┬ couchbase@3.2.2

Originally, pixl-server-storage was 2.0.20. I installed 2.0.10 specifically as mentioned in package.json, still got the same result.

egrep 'couchbase|pixl-server-storage' package.json
		"couchbase": "^3.2.2",
		"pixl-server-storage": "^2.0.10",

### Operating system and version?

cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

uname -a
Linux host 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Node.js version?

node --version
v14.18.0

### Cronicle software version?

v0.8.62

### Are you using a multi-server setup, or just a single server?

Multi-server, hence the couchbase, but I'm not able to get past setting up the storage

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Couchbase

### Can you reproduce the crash consistently?

Yes

## Log Excerpts

Thank you for the assistance!

**Comment by jhuckaby** [comment]
Oh ugh, it looks like Couchbase has changed everything **AGAIN**.  What a pain.  Cronicle is built against Couchbase Client v2.x, and it looks like they've changed everything in the new 3.x branch, which you have.

I'm afraid you'll have to force downgrade it to 2.x, like this:

```
cd /opt/cronicle
npm install couchbase@2.6.12
```

That is, until I can rewrite my storage plugin to support CB v3 API, ugh!!!  What a pain.

Thank you for bringing this to my attention.  I will leave this issue open until I can find the time to support CB v3.
