### ISSUE TITLE
Error: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by mihha** [jhuckaby/Cronicle#462]
## Summary

./control.sh upgrade

Cronicle Installer v1.3
Copyright (c) 2015 - 2018 PixlCore.com. MIT Licensed.
Log File: /opt/cronicle/logs/install.log

Fetching release list...
Upgrading Cronicle from v0.8.62 to v0.9.0...

/opt/cronicle/bin/control.sh stop: Cronicle Daemon stopped

Updating dependencies...
Running post-install script...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'mkdirp'
Require stack:
- /opt/cronicle/bin/build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/opt/cronicle/bin/build.js:12:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/cronicle/bin/build.js' ]
}

ERROR: Failed to run post-install: Error: Command failed: node bin/build.js dist
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'mkdirp'
Require stack:
- /opt/cronicle/bin/build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/opt/cronicle/bin/build.js:12:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/cronicle/bin/build.js' ]
}

## Steps to reproduce the problem

./control.sh upgrade

## Your Setup

Normal single server setup

### Operating system and version?

Ubuntu  20.04.3 LTS

### Node.js version?

v16.8.0

### Cronicle software version?

v0.8.62

### Are you using a multi-server setup, or just a single server?
No

### Are you using the filesystem as back-end storage, or S3/Couchbase?
Filesystem

### Can you reproduce the crash consistently?
Yes

## Log Excerpts

cat /opt/cronicle/logs/install.log

Starting install run: Fri Dec 17 2021 06:45:52 GMT+0100 (Central European Standard Time)

Cronicle Installer v1.3
Copyright (c) 2015 - 2018 PixlCore.com. MIT Licensed.
Log File: /opt/cronicle/logs/install.log

Fetching release list...
Releases URL: https://api.github.com/repos/jhuckaby/Cronicle/releases
Upgrading Cronicle from v0.8.62 to v0.9.0...

Tarball URL: https://api.github.com/repos/jhuckaby/Cronicle/tarball/v0.9.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  302k    0  302k    0     0   784k      0 --:--:-- --:--:-- --:--:--  784k
Updating dependencies...
Executing command: npm update --unsafe-perm

added 12 packages, removed 46 packages, changed 40 packages, and audited 136 packages in 17s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.1.4 -> 8.3.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.0>
npm notice Run `npm install -g npm@8.3.0` to update!
npm notice
Running post-install script...
Executing command: node bin/build.js dist
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'mkdirp'
Require stack:
- /opt/cronicle/bin/build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/opt/cronicle/bin/build.js:12:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/cronicle/bin/build.js' ]
}

Executing npm command to restore lost packages: npm install

up to date, audited 136 packages in 1s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

ERROR: Failed to run post-install: Error: Command failed: node bin/build.js dist
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'mkdirp'
Require stack:
- /opt/cronicle/bin/build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/opt/cronicle/bin/build.js:12:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/cronicle/bin/build.js' ]
}

**Comment by jhuckaby** [comment]
GAH, so sorry, I missed one reference to the old mkdirp dependency.  Thank you for the detailed report!  Fixed in v0.9.1.

https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.1
