### ISSUE TITLE
Cronicle crashes when trying to add a new server

### ISSUE THREAD

**Issue by mpatel-cpi** [jhuckaby/Cronicle#49]
## Summary

Cronicle crashes when trying to add new a new server.

## Steps to reproduce the problem

1. New setup of Cronicle on 2 hosts
2. Changed the "Master Group" regex to allow for both hosts to be master eligible
3. Start Cronicle on both hosts
4. When the UI loads click "Add Server..." in the "Admin -> Servers" section

## Your Setup

I was trying a multi-master setup of Cronicle:
1. Installed Cronicle on 2 EC2 hosts that are publicly accessible
2. Using a share NFS storage to store Cronicle data

### Operating system and version?

Ubuntu 16.04

### Node.js version?

v4.2.6

### Cronicle software version?

0.7.5

### Are you using a multi-server setup, or just a single server?
Trying to setup a multi-master setup

### Are you using the filesystem as back-end storage, or S3/Couchbase?
Filesystem

### Can you reproduce the crash consistently?
Yes, see stack trace below.

## Log Excerpts

Errors show in Chrome dev tools console:
```
POST https://eu-qa-cronicle-master-1.ev-chargepoint.com:3013/api/app/add_server net::ERR_EMPTY_RESPONSE

WebSocket connection to 'wss://eu-qa-cronicle-master-1.xyz.com:3013/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSE
```

Contents of logs/crash.log:
```
Thu Nov 30 2017 20:20:00 GMT+0000 (UTC)
TypeError: this is not a typed array.
    at Function.from (native)
    at module.exports.Class.create.post (/opt/cronicle/node_modules/pixl-request/request.js:231:41)
    at module.exports.Class.create.json (/opt/cronicle/node_modules/pixl-request/request.js:112:15)
    at /opt/cronicle/lib/api/admin.js:78:17
    at /opt/cronicle/lib/api.js:354:6
    at /opt/cronicle/node_modules/pixl-server-storage/storage.js:216:4
    at /opt/cronicle/node_modules/pixl-server-storage/engines/Filesystem.js:273:4
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

Thu Nov 30 2017 20:37:34 GMT+0000 (UTC)
TypeError: this is not a typed array.
    at Function.from (native)
    at module.exports.Class.create.post (/opt/cronicle/node_modules/pixl-request/request.js:231:41)
    at module.exports.Class.create.json (/opt/cronicle/node_modules/pixl-request/request.js:112:15)
    at /opt/cronicle/lib/api/admin.js:78:17
    at /opt/cronicle/lib/api.js:354:6
    at /opt/cronicle/node_modules/pixl-server-storage/storage.js:216:4
    at /opt/cronicle/node_modules/pixl-server-storage/engines/Filesystem.js:273:4
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by jhuckaby** [comment]
What a bizarre crash and stack trace.  I cannot fathom what is going wrong there.  I suspect this may have something to do with Node v4 and my use of `Buffer.from()` in [pixl-request](https://github.com/jhuckaby/pixl-request).

As soon as I have some time, I'll try to spin up an Ubuntu 16 box with Node v4 and try to reproduce this.  Thanks for the bug report.

**Comment by jhuckaby** [comment]
Looks like you may have to upgrade to Node v4.5.0 or higher:

https://nodejs.org/docs/v4.5.0/api/buffer.html#buffer_class_method_buffer_from_str_encoding

I try to support older Node versions by checking if `Buffer.from` exists, and falling back to the legacy `new Buffer()` if not:

https://github.com/jhuckaby/pixl-request/blob/master/request.js#L225

But it looks like Node v4.2.6 has only **partial** support for `Buffer.from`.  The method exists, but it doesn't accept conversion from a string, which is what appears to be happening in Cronicle.

Would it be possible for you to upgrade to Node v4.5.0 on your server?  I'm not sure how to support your specific Node version without doing an ugly hack that sniffs the version and applies legacy code.

**Comment by mpatel-cpi** [comment]
Thanks for looking into this. I'll upgrade and let you know how it goes.

**Comment by mpatel-cpi** [comment]
I upgraded node.js to version: v8.9.1 and the error is gone.

However am not able to add the second server as "master". I have:
- updated the "Master Group" regex to include both servers
- All communication between the 2 servers is allowed

Can you let me know what I'm doing wrong and how to proceed?

`https://eu-qa-cronicle-master-1.example.com:3013/api/app/add_server` API call returns:
`{"code":"server","description":"Failed to contact server: Socket Timeout (8000 ms)"}
`
Cronicle.log excerpt from `master-2`:

`
[1512417312.757][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][1][Cronicle v0.7.5 Starting Up][]
[1512417312.761][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][2][Server IP: 172.21.26.4, Daemon PID: 9501][]
[1512417312.762][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][3][Starting component: Storage][]
[1512417312.772][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][3][Starting component: WebServer][]
[1512417312.786][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][3][Starting component: API][]
[1512417312.787][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][3][Starting component: User][]
[1512417312.787][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][3][Starting component: Cronicle][]
[1512417312.787][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][3][Cronicle engine starting up][["/usr/bin/node","/opt/cronicle/lib/main.js"]]
[1512417312.792][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][4][Using broadcast IP: 172.21.27.255][]
[1512417312.792][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][4][Starting UDP server on port: 3014][]
[1512417312.816][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][4][Server not found in cluster -- waiting for a master server to contact us][]
[1512417312.817][2017-12-04 19:55:12][eu-qa-cronicle-master-2.example.com][Cronicle][debug][2][Startup complete, entering main loop][]
`

**Comment by jhuckaby** [comment]
Well, I see a number of potential issues here.  First, it appears that you are trying to use HTTPS.  You should know that **Cronicle doesn't yet support HTTPS**, and there are a ton of open issues around this, especially with server-to-server communication, which appears to be what is failing here.  If you completely disable HTTPS in the Cronicle configuration, this may solve your issue.

Second, it appears that your master server cannot contact your secondary server, as it is getting a TCP socket connect timeout.  This can mean a lot of different things, and there are several things you can try.  You could SSH to one server and try to wget/curl a URL on the other, to see where the problem may lie.

Since the "add_server" API is failing, that means whatever hostname or IP address **you** entered into the dialog box in the UI, cannot be contacted from the master server.  So enter whatever the LAN IP of the server is, so the master server can reach it.

Also, you could try setting one or both of these configuration parameters in your Cronicle configuration:

### server_comm_use_hostnames

Setting this parameter to `1` will force the Cronicle servers to connect to each other using hostnames rather than LAN IP addresses.  This is mainly for special situations where your local server IP addresses may change, and you would prefer to rely on DNS instead.  The default is `0` (disabled), meaning connect using IP addresses.

### web_socket_use_hostnames

Setting this parameter to `1` will force Cronicle's Web UI to connect to the back-end servers using their hostnames rather than IP addresses.  This includes both AJAX API calls and Websocket streams.  You should only need to enable this in special situations where your users cannot access your servers via their LAN IPs, and you need to proxy them through a hostname (DNS) instead.  The default is `0` (disabled), meaning connect using IP addresses.

Good luck!
