### ISSUE TITLE
Cronicle crashing

### ISSUE THREAD

**Issue by tgnelson** [jhuckaby/Cronicle#506]
## Summary
Cronicle crashes with an emergency shutdown

## Steps to reproduce the problem
Nothing specific, started happening randomly a few days ago.

### Operating system and version?
Redhat Enterprise

### Node.js version?
v8.17.0

### Cronicle software version?
Version 0.8.31

### Are you using a multi-server setup, or just a single server?
Single Server
### Are you using the filesystem as back-end storage, or S3/Couchbase?
back-end storage
### Can you reproduce the crash consistently?
No
## Log Excerpts
Fri Jul 08 2022 08:00:23 GMT-0500 (CDT) - rofnoc011a - PID 75864
AssertionError [ERR_ASSERTION]: Wrong number of arguments to doError
    at constructor.doError (/opt/cronicle/node_modules/pixl-server-user/user.js:1305:3)
    at /opt/cronicle/node_modules/pixl-server-user/user.js:308:17
    at /opt/cronicle/node_modules/pixl-server-user/user.js:1281:5
    at /opt/cronicle/node_modules/pixl-server-storage/storage.js:359:4
    at /opt/cronicle/node_modules/pixl-server-storage/engines/Filesystem.js:422:4
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by jhuckaby** [comment]
Hmm, I believe those issues were fixed in a recent release of pixl-server-user.  I can't find anything interesting at those line numbers in the latest version.  But I did find this commit from May:

https://github.com/jhuckaby/pixl-server-user/commit/df939fe31086286b762513349ba03fc9852b0e1f

If you don't want to upgrade your entire Cronicle install, you can try just upgrading the pixl-server-user module.  Try this:

```
sudo bash # become root
cd /opt/cronicle
bin/control.sh stop
rm package-lock.json
npm install pixl-server-user
bin/control.sh start
```
