### ISSUE TITLE
Unable to start worker

### ISSUE THREAD

**Issue by danwillo** [jhuckaby/Cronicle#534]
## Summary

I'm trying to install a primary / worker server setup using docker containers. 
successfully spun up the primary server, which runs fine.
when i then start up an additional container (minus the startup script) I get an error that it cant find the global files.

if I try and copy the data file from the master into the worker it starts up, but as a primary / backup server, and not a worker. am i missing something to tell cronicle to startup as a worker?

## Steps to reproduce the problem

start a local docker container primary using the following docker file 

https://github.com/soulteary/docker-cronicle/blob/main/docker/Dockerfile

start a worker container using the above docker file minus the call to setup.

## Your Setup

Primary with workers

### Operating system and version?

linux containers 

### Node.js version?

Node.js v14.17.5.

### Cronicle software version?

0.9.11

### Are you using the filesystem as back-end storage, or S3/Couchbase?

filesystem

### Can you reproduce the crash consistently?

yes

## Log Excerpts

[1665055082.618][2022-10-06 11:18:02][worker][1][Storage][debug][9][List could not be loaded: global/schedule: Error: Failed to fetch key: global/schedule: File not found][]
[1665055082.618][2022-10-06 11:18:02][worker][1][Storage][debug][9][Removing reader from shared lock: |global/schedule][{"readers":0}]
[1665055082.619][2022-10-06 11:18:02][worker][1][Storage][debug][9][Unlocking key: |global/schedule (0 clients waiting)][]
[1665055082.621][2022-10-06 11:18:02][worker][1][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'length' of null][TypeError: Cannot read property 'length' of null     at /opt/cronicle/lib/scheduler.js:31:35     at /opt/cronicle/node_modules/pixl-server-storage/list.js:503:12     at /opt/cronicle/node_modules/async/dist/async.js:3891:9     at /opt/cronicle/node_modules/async/dist/async.js:473:16     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:991:17)     at /opt/cronicle/node_modules/async/dist/async.js:972:16     at /opt/cronicle/node_modules/async/dist/async.js:3888:13     at /opt/cronicle/node_modules/pixl-server-storage/list.js:488:6     at /opt/cronicle/node_modules/pixl-server-storage/list.js:71:5     at /opt/cronicle/node_modules/pixl-server-storage/storage.js:361:20]
[1665055082.621][2022-10-06 11:18:02][worker][1][Error][error][crash][Emergency Shutdown: TypeError: Cannot read property 'length' of null][]
[1665055082.621][2022-10-06 11:18:02][worker][1][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read property 'length' of null][]
TypeError: Cannot read property 'length' of null
    at /opt/cronicle/lib/scheduler.js:31:35
    at /opt/cronicle/node_modules/pixl-server-storage/list.js:503:12
    at /opt/cronicle/node_modules/async/dist/async.js:3891:9
    at /opt/cronicle/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:991:17)
    at /opt/cronicle/node_modules/async/dist/async.js:972:16
    at /opt/cronicle/node_modules/async/dist/async.js:3888:13
    at /opt/cronicle/node_modules/pixl-server-storage/list.js:488:6
    at /opt/cronicle/node_modules/pixl-server-storage/list.js:71:5
    at /opt/cronicle/node_modules/pixl-server-storage/storage.js:361:20

**Comment by mikeTWC1984** [comment]
I think there is something wrong with entry point of this image. As far as I can see it adds current host to server list, thus doing incomplete setup.  Probably this image wasn't meant to be used as worker. 
You may try to use ```./lib/main.js --echo 1 --foreground 1``` as entry point for your worker

**Comment by mikeTWC1984** [comment]
Also, use tini as your entry point (google how to install it, in alpine it's just "apk add tini")
```Dockerfile
ENTRYPOINT ["/sbin/tini", "--"]
```
Without it cronicle might become zombie process (if you shut it donw/restart from ui)

**Comment by danwillo** [comment]
thanks Mike, we shall give that a go.

incidentally we managed to get a worker running by doing the following:

1. reverted back to a simple docker file which just installs and starts as per instructions
2. Copied data folder and conf.json from primary to worker
3. edited the hostname and ip address in \data\global\af\56 to something different.
4. started cronicle on worker

the worker was then available to be added as a worker server. 
this is not ideal, though so will give the above a go let you know how we get on.

**Comment by mikeTWC1984** [comment]
Actually you shouldn't add data folder for plain worker. All it needs is a secret key matching your master node. Only master node should have access to data. You can have multiple master nodes, but then data folder should be shared (e.g. using NFS)

**Comment by danwillo** [comment]
Yes I thought that was the case, however without the data folder, the service will not start and throws the above exception about missing list items. The conf file is copied as instructed. We also get the same issue using your suggested method.

**Comment by mikeTWC1984** [comment]
Data folder is not needed for worker by design. You likely get that error because of broken entrypoint script. I think what it's doing is adding current machine name to master list, so it looking for data folder, and crashing if not found
You can do a simple test - start plain alpine container in interactive mode, e.g.
```docker run --rm -it -p 3012:3012 alpine sh```
then install cronicle, but skip setup up step (copy bleow command to sh prompt). 
```bash
apk add bash git procps npm nodejs && mkdir /opt/cronicle \
 && git clone https://github.com/jhuckaby/Cronicle /opt/cronicle \
 && cd /opt/cronicle && npm i && node bin/build dist \
 && ./lib/main.js --foreground 1 --echo 1 --secret_key mySecretKey
```
Cronicle will start in worker mode, waiting to be added to a cluster.
