### ISSUE TITLE
Cannot run python script which calls headless chromium

### ISSUE THREAD

**Issue by arminus** [jhuckaby/Cronicle#744]
## Summary

A python script which uses [pyppeteer](https://github.com/pyppeteer/pyppeteer/) which in turn calls a headless chromium fails when being called from cronicle but works fine when being called from system cron.

## Steps to reproduce the problem

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/scripts/pyppeteer/./myscript.py", line 12, in scrape_data
    browser = await launch()
  File "/home/pi/scripts/pyppeteer/.env/lib/python3.9/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/pi/scripts/pyppeteer/.env/lib/python3.9/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/pi/scripts/pyppeteer/.env/lib/python3.9/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```
### Operating system and version?

Linux pi4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### Node.js version?

v20.10.0

### Cronicle software version?

0.9.39

### Are you using a multi-server setup, or just a single server?

single

### Are you using the filesystem as back-end storage, or S3/Couchbase?

filesystem

### Can you reproduce the crash consistently?

yes

**Comment by mikeTWC1984** [comment]
I don't think it's cronicle issue. Brief googling shows that this is related to the issue loading share libraries. Perhaps you need to set LD_LIBRARY_PATH or something in cronicle

**Comment by arminus** [comment]
It's actually simpler. If I run the script with su to my non-root user it works. Strange that this su is not needed when being run from cron, but solved anyhow.
