### ISSUE TITLE
control.sh throws exception when run inside the bin dir

### ISSUE THREAD

**Issue by iambocai** [jhuckaby/Cronicle#8]
Like this:
> [root@host bin]# sh control.sh start 
control.sh start: Starting up Cronicle Daemon...
module.js:474
    throw err;
    ^
> 
> Error: Cannot find module '/opt/cronicle/bin/lib/main.js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
control.sh start: Cronicle Daemon could not be started
[root@host bin]# pwd
/opt/cronicle/bin

fix: #9

**Comment by jhuckaby** [comment]
Thanks for the bug report!  This will be fixed in the next release.
